
server:
  port: 8081
  servlet:
    context-path: /sass
spring:
  swagger:
    enable: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: lc12345
    url: jdbc:mysql://192.168.1.210:3307/data_mining?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zsy